#ifndef DARKCORE_WEBSOCKETS_WEBSOCKETS_HPP
#define DARKCORE_WEBSOCKETS_WEBSOCKETS_HPP

#include "../Platform.hpp"

DWORD WINAPI StartWebSocketServer(LPVOID);

#endif /* DARKCORE_WEBSOCKETS_WEBSOCKETS_HPP */
